## Pandas의 개념 및 활용

In [ ]:
import pandas as pd

df = pd.DataFrame(
    {
        "Name": [
            "Braund, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss. Elizabeth",
        ],
        "Age": [22, 35, 58],
        "Sex": ["male", "male", "female"],
    }
)

df

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

In [ ]:
df = pd.DataFrame(
    {
        "Name": [
            "Braund, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss. Elizabeth",
        ],
        "Age": [22, 35, 58],
        "Sex": ["male", "male", "female"],
    }
)

df['Age']

0    22
1    35
2    58
Name: Age, dtype: int64

In [ ]:
ages = pd.Series(data=[22, 35, 58], name="Age")

print(ages)

0    22
1    35
2    58
Name: Age, dtype: int64

## 데이터 프레임 생성 및 조작

In [ ]:
import pandas as pd

d1 = {
    'Name': ['Jiwon', 'YuJeong', 'Minwoo', 'Jihoon'],
    'Year': [2021, 2024, 2025, 2023],
    'Class': ['Java', 'Data', 'AI', 'Data']
}

# 딕셔너리를 DataFrame으로 변환
data_df = pd.DataFrame(d1)
print(data_df)
print("-"*30)

# 새로운 컬럼명을 추가
data_df = pd.DataFrame(d1, columns=["Name", "Year", "Class", "Age"])
print(data_df)
print("-"*30)

# 인덱스를 새로운 값으로 할당
data_df = pd.DataFrame(d1, index=['one', 'two', 'three', 'four'])
print(data_df)
print("-"*30)

      Name  Year Class
0    Jiwon  2021  Java
1  YuJeong  2024  Data
2   Minwoo  2025    AI
3   Jihoon  2023  Data
------------------------------
      Name  Year Class  Age
0    Jiwon  2021  Java  NaN
1  YuJeong  2024  Data  NaN
2   Minwoo  2025    AI  NaN
3   Jihoon  2023  Data  NaN
------------------------------
          Name  Year Class
one      Jiwon  2021  Java
two    YuJeong  2024  Data
three   Minwoo  2025    AI
four    Jihoon  2023  Data
------------------------------

In [ ]:
# Titanic 데이터 CSV 파일 로드
titanic = pd.read_csv("./data/titanic.csv")

# DataFrame 출력
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# 데이터프레임의 컬럼명 출력
print("columns:", titanic.columns)

# 데이터프레임의 인덱스 출력
print("index:", titanic.index)

# 인덱스 값을 배열 형태로 출력
print("index value:", titanic.index.values[0:100])

columns: Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')
index: RangeIndex(start=0, stop=891, step=1)
index value: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

In [ ]:
# 데이터프레임의 맨 앞부터 일부 데이터만 추출
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# 데이터프레임의 맨 뒤부터 일부 데이터만 추출
titanic.tail(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
# 데이터프레임의 행을 랜덤하게 추출
titanic.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
458,459,1,2,"Toomey, Miss. Ellen",female,50.0,0,0,F.C.C. 13531,10.5000,NaN,S
332,333,0,1,"Graham, Mr. George Edward",male,38.0,0,1,PC 17582,153.4625,C91,S
323,324,1,2,"Caldwell, Mrs. Albert Francis (Sylvia Mae Harb...",female,22.0,1,1,248738,29.0000,NaN,S
184,185,1,3,"Kink-Heilmann, Miss. Luise Gretchen",female,4.0,0,2,315153,22.0250,NaN,S
253,254,0,3,"Lobb, Mr. William Arthur",male,30.0,1,0,A/5. 3336,16.1000,NaN,S

In [ ]:
# 데이터프레임의 행과 열의 크기를 가지고 있는 속성
print('데이터 프레임의 행과 열 크기:', titanic.shape)

데이터 프레임의 행과 열 크기: (891, 12)

In [ ]:
# 데이터프레임의 기본 정보 출력
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
# 데이터프레임의 요약통계 정보 출력
titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
# DataFrame 전체 행을 기준으로 중복된 행이 얼마나 있는지 확인
titanic.value_counts()

PassengerId  Survived  Pclass  Name                                                  Sex     Age   SibSp  Parch  Ticket    Fare      Cabin  Embarked
2            1         1       Cumings, Mrs. John Bradley (Florence Briggs Thayer)   female  38.0  1      0      PC 17599  71.2833   C85    C           1
572          1         1       Appleton, Mrs. Edward Dale (Charlotte Lamson)         female  53.0  2      0      11769     51.4792   C101   S           1
578          1         1       Silvey, Mrs. William Baird (Alice Munger)             female  39.0  1      0      13507     55.9000   E44    S           1
582          1         1       Thayer, Mrs. John Borland (Marian Longstreth Morris)  female  39.0  1      1      17421     110.8833  C68    C           1
584          0         1       Ross, Mr. John Hugo                                   male    36.0  0      0      13049     40.1250   A10    C           1
                                                                                                                                                       ..
328          1         2       Ball, Mrs. (Ada E Hall)                               female  36.0  0      0      28551     13.0000   D      S           1
330          1         1       Hippach, Miss. Jean Gertrude                          female  16.0  0      1      111361    57.9792   B18    C           1
332          0         1       Partner, Mr. Austen                                   male    45.5  0      0      113043    28.5000   C124   S           1
333          0         1       Graham, Mr. George Edward                             male    38.0  0      1      PC 17582  153.4625  C91    S           1
890          1         1       Behr, Mr. Karl Howell                                 male    26.0  0      0      111369    30.0000   C148   C           1
Name: count, Length: 183, dtype: int64

In [ ]:
# 특정 컬럼의 값 개수를 세는 것이 필요할 때 사용하는 방식
titanic['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [ ]:
print("titanic 데이터 건수:", titanic.shape[0])  # 총 데이터 개수 출력

print ("기본 설정인 dropna=True로 value_counts()")
print(titanic["Embarked"].value_counts())  # 기본 설정

print("\n dropna=False로 value_counts()") 
print(titanic["Embarked"].value_counts(dropna=False))  # NaN 포함

titanic 데이터 건수: 891
기본 설정인 dropna=True로 value_counts()
Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

 dropna=False로 value_counts()
Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

In [ ]:
# 새로운 컬럼 `Age_new`를 생성
titanic["Age_new"]=0
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_new
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0

In [ ]:
# 행 삭제시 axis = 0 / 컬럼 삭제시 axis = 1으로 설정
titanic.drop("Age_new", axis=1, inplace=True)
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# 행 삭제 전 데이터 출력
print("before axis=0 drop")
titanic.head()  # 상위 6개 행 출력

before axis=0 drop

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# 특정 행 삭제 (index 0, 1, 2 삭제)
titanic.drop([0, 1, 2], axis=0, inplace=True)

# 삭제 후 데이터 출력
print("after axis=0 drop")
titanic.head()  # 상위 5개 행 출력

after axis=0 drop

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

## 인덱싱 및 필터링

#### 컬럼 기반 필터링

In [ ]:
# [] 연산자 내에 한 개의 컬럼만 입력하면 Series 객체를 반환
series = titanic['Name']
series

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [ ]:
# [] 연산자 내에 한 개의 컬럼을 리스트로 입력하면 DataFrame 반환
one_col_df = titanic[['Name']]
one_col_df

                                                  Name
0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
..                                                 ...
886                              Montvila, Rev. Juozas
887                       Graham, Miss. Margaret Edith
888           Johnston, Miss. Catherine Helen "Carrie"
889                              Behr, Mr. Karl Howell
890                                Dooley, Mr. Patrick

[891 rows x 1 columns]

In [ ]:
# [] 연산자 내에 여러 개의 컬럼을 리스트로 입력하면 그 컬럼들로 구성된 DataFrame 반환
filtered_df = titanic[['Name', 'Age']]
filtered_df

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

####  명칭 / 위치 기반 인덱싱 : loc[ ] / iloc[ ]

In [ ]:
# 인덱스 5번 행의 "Pclass" 열 데이터 출력
value = titanic.loc[5, "Pclass"]
value

3

In [ ]:
# 인덱스 5번 행에서 "Name"과 "Age" 선택
subset = titanic.loc[5, ["Name", "Age"]]
print(subset)

Name    Moran, Mr. James
Age                  NaN
Name: 5, dtype: object

In [ ]:
# 인덱스 5~7번 행에서 "Name", "Age", "Embarked" 선택
subset = titanic.loc[5:7, ["Name", "Age", "Embarked"]]
print(subset)

                             Name   Age Embarked
5                Moran, Mr. James   NaN        Q
6         McCarthy, Mr. Timothy J  54.0        S
7  Palsson, Master. Gosta Leonard   2.0        S

In [ ]:
# iloc[행_위치, 열_위치] → 0부터 시작하는 위치 기반 인덱싱
value = titanic.iloc[5, 1]
value

0

In [ ]:
# 0번 행에서 1~3번째 열 선택 -> Series로 반환
subset = titanic.iloc[0, [1, 2, 3]]
subset

Survived                          0
Pclass                            3
Name        Braund, Mr. Owen Harris
Name: 0, dtype: object

In [ ]:
# 0~2번 행에서 1~3번째 열 선택 -> DataFrame으로 반환
subset = titanic.iloc[0:3, 1:4]
subset

   Survived  Pclass                                               Name
0         0       3                            Braund, Mr. Owen Harris
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2         1       3                             Heikkinen, Miss. Laina

#### 조건식에 따른 필터링 : Boolean Indexing

In [ ]:
# 35살 이상의 나이를 가진 승객 추출
age_above_35 = titanic[titanic['Age'] >= 35]
age_above_35.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

In [ ]:
titanic['Age'] >= 35

0      False
1       True
2      False
3       True
4       True
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [ ]:
age_above_35.shape

(235, 12)

In [ ]:
# "Pclass" 값이 2 또는 3인 승객만 선택
class_23 = titanic[titanic["Pclass"].isin([2, 3])]
class_23.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [ ]:
# "Pclass"가 2 또는 3인 데이터 추출 (OR 연산)
class_23 = titanic[(titanic["Pclass"] == 2) | (titanic["Pclass"] == 3)]
class_23.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [ ]:
# "Age" 컬럼이 NaN이 아닌(값이 존재하는) 행만 필터링
age_no_na = titanic[titanic["Age"].notna()]
age_no_na.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
age_no_na.shape

(714, 12)

In [ ]:
# 조건을 사용한 행과 열 동시 추출 (loc[])
adult_names = titanic.loc[titanic["Age"] > 35, "Name"]
adult_names.head()

1     Cumings, Mrs. John Bradley (Florence Briggs Th...
6                               McCarthy, Mr. Timothy J
11                             Bonnell, Miss. Elizabeth
13                          Andersson, Mr. Anders Johan
15                     Hewlett, Mrs. (Mary D Kingcome)
Name: Name, dtype: object

In [ ]:
# 추가: 특정 행과 열의 값을 변경하는 코드
titanic.iloc[0:3, 3] = "anonymous"

## 데이터 정제 및 전처리

In [ ]:
import pandas as pd

# Titanic 데이터 CSV 파일 로드
titanic = pd.read_csv("./data/titanic.csv")

# DataFrame 출력
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# 전체 결측치 개수 확인
print(titanic.isna().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
# 특정 컬럼(Embarked)에서 결측치가 얼마나 있는지 확인
print(titanic['Embarked'].isna().sum())

2

In [ ]:
pd.isna(titanic)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [ ]:
# 결측치가 있는 행을 제거
clean_df = titanic.dropna(subset=['Embarked'], how='any')

print("결측치 제거 후 데이터 개수:", clean_df.shape[0])
print(clean_df[['Survived', 'Pclass', 'Embarked']].head())

결측치 제거 후 데이터 개수: 889
   Survived  Pclass Embarked
0         0       3        S
1         1       1        C
2         1       3        S
3         1       1        S
4         0       3        S

In [ ]:
# Embarked 컬럼의 최빈값 확인
most_freq = titanic['Embarked'].value_counts().idxmax()

# 결측치를 최빈값으로 채우기
filled_df = titanic.fillna({'Embarked': most_freq})

print("Embarked 결측치 채운 후:", filled_df['Embarked'].isna().sum())
print(filled_df[['Survived', 'Pclass', 'Embarked']].head())

Embarked 결측치 채운 후: 0
   Survived  Pclass Embarked
0         0       3        S
1         1       1        C
2         1       3        S
3         1       1        S
4         0       3        S

## 데이터 처리

In [ ]:
import numpy as np
import pandas as pd

s = pd.Series([1, 3, 5, np.nan, 6, 8])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [ ]:
dates = pd.date_range("20130101", periods=6)
print(dates)

df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
print(df)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
                   A         B         C         D
2013-01-01 -1.236418 -1.935236 -0.558673 -0.059824
2013-01-02  0.354983  0.053965  1.327119 -2.138239
2013-01-03 -0.491612 -1.085243 -0.062719 -1.004057
2013-01-04 -1.318708  1.949848 -0.387481 -1.092749
2013-01-05  0.750034  0.996484  0.040820  0.643811
2013-01-06  0.221883 -2.490948  1.411351 -0.212287

In [ ]:
df2 = pd.DataFrame({
    "A": 1.0,
    "B": pd.Timestamp("20130102"),
    "C": pd.Series(1, index=list(range(4)), dtype="float32"),
    "D": np.array([3] * 4, dtype="int32"),
    "E": pd.Categorical(["test", "train", "test", "train"]),
    "F": "foo"
})
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [ ]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [ ]:
print(df.head(3))     # 상위 3개 행
print(df.tail(3))    # 하위 3개 행

                   A         B         C         D
2013-01-01 -1.236418 -1.935236 -0.558673 -0.059824
2013-01-02  0.354983  0.053965  1.327119 -2.138239
2013-01-03 -0.491612 -1.085243 -0.062719 -1.004057
                   A         B         C         D
2013-01-04 -1.318708  1.949848 -0.387481 -1.092749
2013-01-05  0.750034  0.996484  0.040820  0.643811
2013-01-06  0.221883 -2.490948  1.411351 -0.212287

In [ ]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [ ]:
df_to_numpy = df.to_numpy()
print(df_to_numpy)
print(type(df_to_numpy))

[[-1.23641837 -1.93523588 -0.55867275 -0.05982436]
 [ 0.35498306  0.05396453  1.32711933 -2.13823854]
 [-0.49161166 -1.08524312 -0.06271887 -1.0040571 ]
 [-1.31870815  1.94984761 -0.38748118 -1.09274924]
 [ 0.75003403  0.99648418  0.04081953  0.64381123]
 [ 0.22188317 -2.49094777  1.41135084 -0.21228718]]
<class 'numpy.ndarray'>

In [ ]:
print(df.describe())

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.286640 -0.418522  0.295069 -0.643891
std    0.866513  1.724793  0.860072  0.974665
min   -1.318708 -2.490948 -0.558673 -2.138239
25%   -1.050217 -1.722738 -0.306291 -1.070576
50%   -0.134864 -0.515639 -0.010950 -0.608172
75%    0.321708  0.760854  1.005544 -0.097940
max    0.750034  1.949848  1.411351  0.643811

In [ ]:
print(df.T)

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -1.236418    0.354983   -0.491612   -1.318708    0.750034    0.221883
B   -1.935236    0.053965   -1.085243    1.949848    0.996484   -2.490948
C   -0.558673    1.327119   -0.062719   -0.387481    0.040820    1.411351
D   -0.059824   -2.138239   -1.004057   -1.092749    0.643811   -0.212287

In [ ]:
print(df["A"])

2013-01-01   -1.236418
2013-01-02    0.354983
2013-01-03   -0.491612
2013-01-04   -1.318708
2013-01-05    0.750034
2013-01-06    0.221883
Freq: D, Name: A, dtype: float64

In [ ]:
df[0:3]

                   A         B         C         D
2013-01-01 -1.236418 -1.935236 -0.558673 -0.059824
2013-01-02  0.354983  0.053965  1.327119 -2.138239
2013-01-03 -0.491612 -1.085243 -0.062719 -1.004057

In [ ]:
df["20130102":"20130104"]

                   A         B         C         D
2013-01-02  0.354983  0.053965  1.327119 -2.138239
2013-01-03 -0.491612 -1.085243 -0.062719 -1.004057
2013-01-04 -1.318708  1.949848 -0.387481 -1.092749

In [ ]:
df.loc["20130102":"20130104", ["A", "B"]]

                   A         B
2013-01-02  0.354983  0.053965
2013-01-03 -0.491612 -1.085243
2013-01-04 -1.318708  1.949848

In [ ]:
df.loc[dates[0], "A"]       # 위치 기반 접근

-1.2364183693526707

In [ ]:
df.at[dates[0], "A"]        # 가장 빠른 방식

-1.2364183693526707

In [ ]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ["E"])
df1.loc[dates[0] : dates[1], "E"] = 1
print(df1)

                   A         B         C         D    E
2013-01-01 -1.236418 -1.935236 -0.558673 -0.059824  1.0
2013-01-02  0.354983  0.053965  1.327119 -2.138239  1.0
2013-01-03 -0.491612 -1.085243 -0.062719 -1.004057  NaN
2013-01-04 -1.318708  1.949848 -0.387481 -1.092749  NaN

## 데이터 정렬

In [ ]:
import pandas as pd

# Titanic 데이터 CSV 파일 로드
titanic = pd.read_csv("./data/titanic.csv")

# DataFrame 출력
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
# 이름 기준 오름차순 정렬
titanic_sorted = titanic.sort_values(by=['Name'], ascending=True)
titanic_sorted.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
845,846,0,3,"Abbing, Mr. Anthony",male,42.0,0,0,C.A. 5547,7.55,NaN,S
746,747,0,3,"Abbott, Mr. Rossmore Edward",male,16.0,1,1,C.A. 2673,20.25,NaN,S
279,280,1,3,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35.0,1,1,C.A. 2673,20.25,NaN,S

In [ ]:
# Pclass와 Name 기준 내림차순 정렬
titanic_sorted = titanic.sort_values(by=['Pclass', 'Name'], ascending=False)
titanic_sorted.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5,NaN,S
282,283,0,3,"de Pelsmaeker, Mr. Alfons",male,16.0,0,0,345778,9.5,NaN,S

In [ ]:
print(titanic['Pclass'].nunique())
print(titanic['Pclass'].unique())

3
[3 1 2]

In [ ]:
print(titanic['Survived'].nunique())
print(titanic['Survived'].unique())

2
[0 1]

In [ ]:
print(titanic['Name'].nunique())
print(titanic['Name'].unique())

891
['Braund, Mr. Owen Harris'
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'
 'Heikkinen, Miss. Laina' 'Futrelle, Mrs. Jacques Heath (Lily May Peel)'
 'Allen, Mr. William Henry' 'Moran, Mr. James' 'McCarthy, Mr. Timothy J'
 'Palsson, Master. Gosta Leonard'
 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)'
 'Nasser, Mrs. Nicholas (Adele Achem)' 'Sandstrom, Miss. Marguerite Rut'
 'Bonnell, Miss. Elizabeth' 'Saundercock, Mr. William Henry'
 'Andersson, Mr. Anders Johan' 'Vestrom, Miss. Hulda Amanda Adolfina'
 'Hewlett, Mrs. (Mary D Kingcome) ' 'Rice, Master. Eugene'
 'Williams, Mr. Charles Eugene'
 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)'
 'Masselmani, Mrs. Fatima' 'Fynney, Mr. Joseph J' 'Beesley, Mr. Lawrence'
 'McGowan, Miss. Anna "Annie"' 'Sloper, Mr. William Thompson'
 'Palsson, Miss. Torborg Danira'
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)'
 'Emir, Mr. Farred Chehab' 'Fortune, Mr. Charles Alexander'
 'O\'Dwyer, Miss. Ellen "Nellie"' 'Todoroff, Mr. Lalio'
 'Uruchurtu, Don. Manuel E'
 'Spencer, Mrs. William Augustus (Marie Eugenie)'
 'Glynn, Miss. Mary Agatha' 'Wheadon, Mr. Edward H'
 'Meyer, Mr. Edgar Joseph' 'Holverson, Mr. Alexander Oskar'
 'Mamee, Mr. Hanna' 'Cann, Mr. Ernest Charles'
 'Vander Planke, Miss. Augusta Maria' 'Nicola-Yarred, Miss. Jamila'
 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)'
 'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)'
 'Kraeff, Mr. Theodor' 'Laroche, Miss. Simonne Marie Anne Andree'
 'Devaney, Miss. Margaret Delia' 'Rogers, Mr. William John'
 'Lennon, Mr. Denis' "O'Driscoll, Miss. Bridget" 'Samaan, Mr. Youssef'
 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)'
 'Panula, Master. Juha Niilo' 'Nosworthy, Mr. Richard Cater'
 'Harper, Mrs. Henry Sleeper (Myna Haxtun)'
 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)'
 'Ostby, Mr. Engelhart Cornelius' 'Woolner, Mr. Hugh' 'Rugg, Miss. Emily'
 'Novel, Mr. Mansouer' 'West, Miss. Constance Mirium'
 'Goodwin, Master. William Frederick' 'Sirayanian, Mr. Orsen'
 'Icard, Miss. Amelie' 'Harris, Mr. Henry Birkhardt'
 'Skoog, Master. Harald' 'Stewart, Mr. Albert A'
 'Moubarek, Master. Gerios' 'Nye, Mrs. (Elizabeth Ramell)'
 'Crease, Mr. Ernest James' 'Andersson, Miss. Erna Alexandra'
 'Kink, Mr. Vincenz' 'Jenkin, Mr. Stephen Curnow'
 'Goodwin, Miss. Lillian Amy' 'Hood, Mr. Ambrose Jr'
 'Chronopoulos, Mr. Apostolos' 'Bing, Mr. Lee' 'Moen, Mr. Sigurd Hansen'
 'Staneff, Mr. Ivan' 'Moutal, Mr. Rahamin Haim'
 'Caldwell, Master. Alden Gates' 'Dowdell, Miss. Elizabeth'
 'Waelens, Mr. Achille' 'Sheerlinck, Mr. Jan Baptist'
 'McDermott, Miss. Brigdet Delia' 'Carrau, Mr. Francisco M'
 'Ilett, Miss. Bertha'
 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)'
 'Ford, Mr. William Neal' 'Slocovski, Mr. Selman Francis'
 'Fortune, Miss. Mabel Helen' 'Celotti, Mr. Francesco'
 'Christmann, Mr. Emil' 'Andreasson, Mr. Paul Edvin'
 'Chaffee, Mr. Herbert Fuller' 'Dean, Mr. Bertram Frank'
 'Coxon, Mr. Daniel' 'Shorney, Mr. Charles Joseph'
 'Goldschmidt, Mr. George B' 'Greenfield, Mr. William Bertram'
 'Doling, Mrs. John T (Ada Julia Bone)' 'Kantor, Mr. Sinai'
 'Petranec, Miss. Matilda' 'Petroff, Mr. Pastcho ("Pentcho")'
 'White, Mr. Richard Frasar' 'Johansson, Mr. Gustaf Joel'
 'Gustafsson, Mr. Anders Vilhelm' 'Mionoff, Mr. Stoytcho'
 'Salkjelsvik, Miss. Anna Kristine' 'Moss, Mr. Albert Johan'
 'Rekic, Mr. Tido' 'Moran, Miss. Bertha' 'Porter, Mr. Walter Chamberlain'
 'Zabour, Miss. Hileni' 'Barton, Mr. David John' 'Jussila, Miss. Katriina'
 'Attalah, Miss. Malake' 'Pekoniemi, Mr. Edvard' 'Connors, Mr. Patrick'
 'Turpin, Mr. William John Robert' 'Baxter, Mr. Quigg Edmond'
 'Andersson, Miss. Ellis Anna Maria' 'Hickman, Mr. Stanley George'
 'Moore, Mr. Leonard Charles' 'Nasser, Mr. Nicholas' 'Webber, Miss. Susan'
 'White, Mr. Percival Wayland' 'Nicola-Yarred, Master. Elias'
 'McMahon, Mr. Martin' 'Madsen, Mr. Fridtjof Arne' 'Peter, Miss. Anna'
 'Ekstrom, Mr. Johan' 'Drazenoic, Mr. Jozef'
 'Coelho, Mr. Domingos Fernandeo'
 'Robins, Mrs. Alexander A (Grace Charity Laury)'
 'Weisz, Mrs. Leopold (Mathilde Francoise Pede)'
 'Sobey, Mr. Samuel James Hayden' 'Richard, Mr. Emile'
 'Newsom, Miss. Helen Monypeny' 'Futrelle, Mr. Jacques Heath'
 'Osen, Mr. Olaf Elon' 'Giglio, Mr. Victor'
 'Boulos, Mrs. Joseph (Sultana)' 'Nysten, Miss. Anna Sofia'
 'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)'
 'Burke, Mr. Jeremiah' 'Andrew, Mr. Edgardo Samuel'
 'Nicholls, Mr. Joseph Charles'
 'Andersson, Mr. August Edvard ("Wennerstrom")'
 'Ford, Miss. Robina Maggie "Ruby"'
 'Navratil, Mr. Michel ("Louis M Hoffman")'
 'Byles, Rev. Thomas Roussel Davids' 'Bateman, Rev. Robert James'
 'Pears, Mrs. Thomas (Edith Wearne)' 'Meo, Mr. Alfonzo'
 'van Billiard, Mr. Austin Blyler' 'Olsen, Mr. Ole Martin'
 'Williams, Mr. Charles Duane' 'Gilnagh, Miss. Katherine "Katie"'
 'Corn, Mr. Harry' 'Smiljanic, Mr. Mile' 'Sage, Master. Thomas Henry'
 'Cribb, Mr. John Hatfield'
 'Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)'
 'Bengtsson, Mr. John Viktor' 'Calic, Mr. Jovo'
 'Panula, Master. Eino Viljami'
 'Goldsmith, Master. Frank John William "Frankie"'
 'Chibnall, Mrs. (Edith Martha Bowerman)'
 'Skoog, Mrs. William (Anna Bernhardina Karlsson)' 'Baumann, Mr. John D'
 'Ling, Mr. Lee' 'Van der hoef, Mr. Wyckoff' 'Rice, Master. Arthur'
 'Johnson, Miss. Eleanor Ileen' 'Sivola, Mr. Antti Wilhelm'
 'Smith, Mr. James Clinch' 'Klasen, Mr. Klas Albin'
 'Lefebre, Master. Henry Forbes' 'Isham, Miss. Ann Elizabeth'
 'Hale, Mr. Reginald' 'Leonard, Mr. Lionel' 'Sage, Miss. Constance Gladys'
 'Pernot, Mr. Rene' 'Asplund, Master. Clarence Gustaf Hugo'
 'Becker, Master. Richard F' 'Kink-Heilmann, Miss. Luise Gretchen'
 'Rood, Mr. Hugh Roscoe'
 'O\'Brien, Mrs. Thomas (Johanna "Hannah" Godfrey)'
 'Romaine, Mr. Charles Hallace ("Mr C Rolmane")' 'Bourke, Mr. John'
 'Turcin, Mr. Stjepan' 'Pinsky, Mrs. (Rosa)' 'Carbines, Mr. William'
 'Andersen-Jensen, Miss. Carla Christine Nielsine'
 'Navratil, Master. Michel M' 'Brown, Mrs. James Joseph (Margaret Tobin)'
 'Lurette, Miss. Elise' 'Mernagh, Mr. Robert'
 'Olsen, Mr. Karl Siegwart Andreas' 'Madigan, Miss. Margaret "Maggie"'
 'Yrois, Miss. Henriette ("Mrs Harbeck")' 'Vande Walle, Mr. Nestor Cyriel'
 'Sage, Mr. Frederick' 'Johanson, Mr. Jakob Alfred' 'Youseff, Mr. Gerious'
 'Cohen, Mr. Gurshon "Gus"' 'Strom, Miss. Telma Matilda'
 'Backstrom, Mr. Karl Alfred' 'Albimona, Mr. Nassef Cassem'
 'Carr, Miss. Helen "Ellen"' 'Blank, Mr. Henry' 'Ali, Mr. Ahmed'
 'Cameron, Miss. Clear Annie' 'Perkin, Mr. John Henry'
 'Givard, Mr. Hans Kristensen' 'Kiernan, Mr. Philip'
 'Newell, Miss. Madeleine' 'Honkanen, Miss. Eliina'
 'Jacobsohn, Mr. Sidney Samuel' 'Bazzani, Miss. Albina'
 'Harris, Mr. Walter' 'Sunderland, Mr. Victor Francis'
 'Bracken, Mr. James H' 'Green, Mr. George Henry' 'Nenkoff, Mr. Christo'
 'Hoyt, Mr. Frederick Maxfield' 'Berglund, Mr. Karl Ivar Sven'
 'Mellors, Mr. William John' 'Lovell, Mr. John Hall ("Henry")'
 'Fahlstrom, Mr. Arne Jonas' 'Lefebre, Miss. Mathilde'
 'Harris, Mrs. Henry Birkhardt (Irene Wallach)' 'Larsson, Mr. Bengt Edvin'
 'Sjostedt, Mr. Ernst Adolf' 'Asplund, Miss. Lillian Gertrud'
 'Leyson, Mr. Robert William Norman' 'Harknett, Miss. Alice Phoebe'
 'Hold, Mr. Stephen' 'Collyer, Miss. Marjorie "Lottie"'
 'Pengelly, Mr. Frederick William' 'Hunt, Mr. George Henry'
 'Zabour, Miss. Thamine' 'Murphy, Miss. Katherine "Kate"'
 'Coleridge, Mr. Reginald Charles' 'Maenpaa, Mr. Matti Alexanteri'
 'Attalah, Mr. Sleiman' 'Minahan, Dr. William Edward'
 'Lindahl, Miss. Agda Thorilda Viktoria' 'Hamalainen, Mrs. William (Anna)'
 'Beckwith, Mr. Richard Leonard' 'Carter, Rev. Ernest Courtenay'
 'Reed, Mr. James George' 'Strom, Mrs. Wilhelm (Elna Matilda Persson)'
 'Stead, Mr. William Thomas' 'Lobb, Mr. William Arthur'
 'Rosblom, Mrs. Viktor (Helena Wilhelmina)'
 'Touma, Mrs. Darwis (Hanne Youssef Razi)'
 'Thorne, Mrs. Gertrude Maybelle' 'Cherry, Miss. Gladys'
 'Ward, Miss. Anna' 'Parrish, Mrs. (Lutie Davis)' 'Smith, Mr. Thomas'
 'Asplund, Master. Edvin Rojj Felix' 'Taussig, Mr. Emil'
 'Harrison, Mr. William' 'Henry, Miss. Delia' 'Reeves, Mr. David'
 'Panula, Mr. Ernesti Arvid' 'Persson, Mr. Ernst Ulrik'
 'Graham, Mrs. William Thompson (Edith Junkins)' 'Bissette, Miss. Amelia'
 'Cairns, Mr. Alexander' 'Tornquist, Mr. William Henry'
 'Mellinger, Mrs. (Elizabeth Anne Maidment)' 'Natsch, Mr. Charles H'
 'Healy, Miss. Hanora "Nora"' 'Andrews, Miss. Kornelia Theodosia'
 'Lindblom, Miss. Augusta Charlotta' 'Parkes, Mr. Francis "Frank"'
 'Rice, Master. Eric' 'Abbott, Mrs. Stanton (Rosa Hunt)'
 'Duane, Mr. Frank' 'Olsson, Mr. Nils Johan Goransson'
 'de Pelsmaeker, Mr. Alfons' 'Dorking, Mr. Edward Arthur'
 'Smith, Mr. Richard William' 'Stankovic, Mr. Ivan'
 'de Mulder, Mr. Theodore' 'Naidenoff, Mr. Penko' 'Hosono, Mr. Masabumi'
 'Connolly, Miss. Kate' 'Barber, Miss. Ellen "Nellie"'
 'Bishop, Mrs. Dickinson H (Helen Walton)' 'Levy, Mr. Rene Jacques'
 'Haas, Miss. Aloisia' 'Mineff, Mr. Ivan' 'Lewy, Mr. Ervin G'
 'Hanna, Mr. Mansour' 'Allison, Miss. Helen Loraine'
 'Saalfeld, Mr. Adolphe' 'Baxter, Mrs. James (Helene DeLaudeniere Chaput)'
 'Kelly, Miss. Anna Katherine "Annie Kate"' 'McCoy, Mr. Bernard'
 'Johnson, Mr. William Cahoone Jr' 'Keane, Miss. Nora A'
 'Williams, Mr. Howard Hugh "Harry"' 'Allison, Master. Hudson Trevor'
 'Fleming, Miss. Margaret'
 'Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)'
 'Abelson, Mr. Samuel' 'Francatelli, Miss. Laura Mabel'
 'Hays, Miss. Margaret Bechstein' 'Ryerson, Miss. Emily Borie'
 'Lahtinen, Mrs. William (Anna Sylfven)' 'Hendekovic, Mr. Ignjac'
 'Hart, Mr. Benjamin' 'Nilsson, Miss. Helmina Josefina'
 'Kantor, Mrs. Sinai (Miriam Sternin)' 'Moraweck, Dr. Ernest'
 'Wick, Miss. Mary Natalie'
 'Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)'
 'Dennis, Mr. Samuel' 'Danoff, Mr. Yoto' 'Slayter, Miss. Hilda Mary'
 'Caldwell, Mrs. Albert Francis (Sylvia Mae Harbaugh)'
 'Sage, Mr. George John Jr' 'Young, Miss. Marie Grice'
 'Nysveen, Mr. Johan Hansen' 'Ball, Mrs. (Ada E Hall)'
 'Goldsmith, Mrs. Frank John (Emily Alice Brown)'
 'Hippach, Miss. Jean Gertrude' 'McCoy, Miss. Agnes' 'Partner, Mr. Austen'
 'Graham, Mr. George Edward' 'Vander Planke, Mr. Leo Edmondus'
 'Frauenthal, Mrs. Henry William (Clara Heinsheimer)' 'Denkoff, Mr. Mitto'
 'Pears, Mr. Thomas Clinton' 'Burns, Miss. Elizabeth Margaret'
 'Dahl, Mr. Karl Edwart' 'Blackwell, Mr. Stephen Weart'
 'Navratil, Master. Edmond Roger' 'Fortune, Miss. Alice Elizabeth'
 'Collander, Mr. Erik Gustaf' 'Sedgwick, Mr. Charles Frederick Waddington'
 'Fox, Mr. Stanley Hubert' 'Brown, Miss. Amelia "Mildred"'
 'Smith, Miss. Marion Elsie' 'Davison, Mrs. Thomas Henry (Mary E Finck)'
 'Coutts, Master. William Loch "William"' 'Dimic, Mr. Jovan'
 'Odahl, Mr. Nils Martin' 'Williams-Lambert, Mr. Fletcher Fellows'
 'Elias, Mr. Tannous' 'Arnold-Franchi, Mr. Josef' 'Yousif, Mr. Wazli'
 'Vanden Steen, Mr. Leo Peter' 'Bowerman, Miss. Elsie Edith'
 'Funk, Miss. Annie Clemmer' 'McGovern, Miss. Mary'
 'Mockler, Miss. Helen Mary "Ellie"' 'Skoog, Mr. Wilhelm'
 'del Carlo, Mr. Sebastiano' 'Barbara, Mrs. (Catherine David)'
 'Asim, Mr. Adola' "O'Brien, Mr. Thomas" 'Adahl, Mr. Mauritz Nils Martin'
 'Warren, Mrs. Frank Manley (Anna Sophia Atkinson)'
 'Moussa, Mrs. (Mantoura Boulos)' 'Jermyn, Miss. Annie'
 'Aubart, Mme. Leontine Pauline' 'Harder, Mr. George Achilles'
 'Wiklund, Mr. Jakob Alfred' 'Beavan, Mr. William Thomas'
 'Ringhini, Mr. Sante' 'Palsson, Miss. Stina Viola'
 'Meyer, Mrs. Edgar Joseph (Leila Saks)' 'Landergren, Miss. Aurora Adelia'
 'Widener, Mr. Harry Elkins' 'Betros, Mr. Tannous'
 'Gustafsson, Mr. Karl Gideon' 'Bidois, Miss. Rosalie'
 'Nakid, Miss. Maria ("Mary")' 'Tikkanen, Mr. Juho'
 'Holverson, Mrs. Alexander Oskar (Mary Aline Towner)'
 'Plotcharsky, Mr. Vasil' 'Davies, Mr. Charles Henry'
 'Goodwin, Master. Sidney Leonard' 'Buss, Miss. Kate'
 'Sadlier, Mr. Matthew' 'Lehmann, Miss. Bertha'
 'Carter, Mr. William Ernest' 'Jansson, Mr. Carl Olof'
 'Gustafsson, Mr. Johan Birger' 'Newell, Miss. Marjorie'
 'Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengtsson)'
 'Johansson, Mr. Erik' 'Olsson, Miss. Elina' 'McKane, Mr. Peter David'
 'Pain, Dr. Alfred' 'Trout, Mrs. William H (Jessie L)'
 'Niskanen, Mr. Juha' 'Adams, Mr. John' 'Jussila, Miss. Mari Aina'
 'Hakkarainen, Mr. Pekka Pietari' 'Oreskovic, Miss. Marija'
 'Gale, Mr. Shadrach' 'Widegren, Mr. Carl/Charles Peter'
 'Richards, Master. William Rowe' 'Birkeland, Mr. Hans Martin Monsen'
 'Lefebre, Miss. Ida' 'Sdycoff, Mr. Todor' 'Hart, Mr. Henry'
 'Minahan, Miss. Daisy E' 'Cunningham, Mr. Alfred Fleming'
 'Sundman, Mr. Johan Julian' 'Meek, Mrs. Thomas (Annie Louise Rowley)'
 'Drew, Mrs. James Vivian (Lulu Thorne Christian)'
 'Silven, Miss. Lyyli Karoliina' 'Matthews, Mr. William John'
 'Van Impe, Miss. Catharina' 'Gheorgheff, Mr. Stanio'
 'Charters, Mr. David' 'Zimmerman, Mr. Leo'
 'Danbom, Mrs. Ernst Gilbert (Anna Sigrid Maria Brogren)'
 'Rosblom, Mr. Viktor Richard' 'Wiseman, Mr. Phillippe'
 'Clarke, Mrs. Charles V (Ada Maria Winfield)'
 'Phillips, Miss. Kate Florence ("Mrs Kate Louise Phillips Marshall")'
 'Flynn, Mr. James' 'Pickard, Mr. Berk (Berk Trembisky)'
 'Bjornstrom-Steffansson, Mr. Mauritz Hakan'
 'Thorneycroft, Mrs. Percival (Florence Kate White)'
 'Louch, Mrs. Charles Alexander (Alice Adelaide Slow)'
 'Kallio, Mr. Nikolai Erland' 'Silvey, Mr. William Baird'
 'Carter, Miss. Lucile Polk' 'Ford, Miss. Doolina Margaret "Daisy"'
 'Richards, Mrs. Sidney (Emily Hocking)' 'Fortune, Mr. Mark'
 'Kvillner, Mr. Johan Henrik Johannesson'
 'Hart, Mrs. Benjamin (Esther Ada Bloomfield)' 'Hampe, Mr. Leon'
 'Petterson, Mr. Johan Emil' 'Reynaldo, Ms. Encarnacion'
 'Johannesen-Bratthammer, Mr. Bernt' 'Dodge, Master. Washington'
 'Mellinger, Miss. Madeleine Violet' 'Seward, Mr. Frederic Kimber'
 'Baclini, Miss. Marie Catherine' 'Peuchen, Major. Arthur Godfrey'
 'West, Mr. Edwy Arthur' 'Hagland, Mr. Ingvald Olai Olsen'
 'Foreman, Mr. Benjamin Laventall' 'Goldenberg, Mr. Samuel L'
 'Peduzzi, Mr. Joseph' 'Jalsevac, Mr. Ivan' 'Millet, Mr. Francis Davis'
 'Kenyon, Mrs. Frederick R (Marion)' 'Toomey, Miss. Ellen'
 "O'Connor, Mr. Maurice" 'Anderson, Mr. Harry' 'Morley, Mr. William'
 'Gee, Mr. Arthur H' 'Milling, Mr. Jacob Christian' 'Maisner, Mr. Simon'
 'Goncalves, Mr. Manuel Estanslas' 'Campbell, Mr. William'
 'Smart, Mr. John Montgomery' 'Scanlan, Mr. James'
 'Baclini, Miss. Helene Barbara' 'Keefe, Mr. Arthur' 'Cacic, Mr. Luka'
 'West, Mrs. Edwy Arthur (Ada Mary Worth)'
 'Jerwan, Mrs. Amin S (Marie Marthe Thuillard)'
 'Strandberg, Miss. Ida Sofia' 'Clifford, Mr. George Quincy'
 'Renouf, Mr. Peter Henry' 'Braund, Mr. Lewis Richard'
 'Karlsson, Mr. Nils August' 'Hirvonen, Miss. Hildur E'
 'Goodwin, Master. Harold Victor' 'Frost, Mr. Anthony Wood "Archie"'
 'Rouse, Mr. Richard Henry' 'Turkula, Mrs. (Hedwig)'
 'Bishop, Mr. Dickinson H' 'Lefebre, Miss. Jeannie'
 'Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)'
 'Kent, Mr. Edward Austin' 'Somerton, Mr. Francis William'
 'Coutts, Master. Eden Leslie "Neville"'
 'Hagland, Mr. Konrad Mathias Reiersen' 'Windelov, Mr. Einar'
 'Molson, Mr. Harry Markland' 'Artagaveytia, Mr. Ramon'
 'Stanley, Mr. Edward Roland' 'Yousseff, Mr. Gerious'
 'Eustis, Miss. Elizabeth Mussey' 'Shellard, Mr. Frederick William'
 'Allison, Mrs. Hudson J C (Bessie Waldo Daniels)' 'Svensson, Mr. Olof'
 'Calic, Mr. Petar' 'Canavan, Miss. Mary' "O'Sullivan, Miss. Bridget Mary"
 'Laitinen, Miss. Kristina Sofia' 'Maioni, Miss. Roberta'
 'Penasco y Castellana, Mr. Victor de Satode'
 'Quick, Mrs. Frederick Charles (Jane Richards)'
 'Bradley, Mr. George ("George Arthur Brayton")'
 'Olsen, Mr. Henry Margido' 'Lang, Mr. Fang' 'Daly, Mr. Eugene Patrick'
 'Webber, Mr. James' 'McGough, Mr. James Robert'
 'Rothschild, Mrs. Martin (Elizabeth L. Barrett)' 'Coleff, Mr. Satio'
 'Walker, Mr. William Anderson' 'Lemore, Mrs. (Amelia Milley)'
 'Ryan, Mr. Patrick'
 'Angle, Mrs. William A (Florence "Mary" Agnes Hughes)'
 'Pavlovic, Mr. Stefo' 'Perreault, Miss. Anne' 'Vovk, Mr. Janko'
 'Lahoud, Mr. Sarkis' 'Hippach, Mrs. Louis Albert (Ida Sophia Fischer)'
 'Kassem, Mr. Fared' 'Farrell, Mr. James' 'Ridsdale, Miss. Lucy'
 'Farthing, Mr. John' 'Salonen, Mr. Johan Werner'
 'Hocking, Mr. Richard George' 'Quick, Miss. Phyllis May'
 'Toufik, Mr. Nakli' 'Elias, Mr. Joseph Jr'
 'Peter, Mrs. Catherine (Catherine Rizk)' 'Cacic, Miss. Marija'
 'Hart, Miss. Eva Miriam' 'Butt, Major. Archibald Willingham'
 'LeRoy, Miss. Bertha' 'Risien, Mr. Samuel Beard'
 'Frolicher, Miss. Hedwig Margaritha' 'Crosby, Miss. Harriet R'
 'Andersson, Miss. Ingeborg Constanzia'
 'Andersson, Miss. Sigrid Elisabeth' 'Beane, Mr. Edward'
 'Douglas, Mr. Walter Donald' 'Nicholson, Mr. Arthur Ernest'
 'Beane, Mrs. Edward (Ethel Clarke)' 'Padro y Manent, Mr. Julian'
 'Goldsmith, Mr. Frank John' 'Davies, Master. John Morgan Jr'
 'Thayer, Mr. John Borland Jr' 'Sharp, Mr. Percival James R'
 "O'Brien, Mr. Timothy" 'Leeni, Mr. Fahim ("Philip Zenni")'
 'Ohman, Miss. Velin' 'Wright, Mr. George'
 'Duff Gordon, Lady. (Lucille Christiana Sutherland) ("Mrs Morgan")'
 'Robbins, Mr. Victor' 'Taussig, Mrs. Emil (Tillie Mandelbaum)'
 'de Messemaeker, Mrs. Guillaume Joseph (Emma)' 'Morrow, Mr. Thomas Rowan'
 'Sivic, Mr. Husein' 'Norman, Mr. Robert Douglas' 'Simmons, Mr. John'
 'Meanwell, Miss. (Marion Ogden)' 'Davies, Mr. Alfred J'
 'Stoytcheff, Mr. Ilia' 'Palsson, Mrs. Nils (Alma Cornelia Berglund)'
 'Doharr, Mr. Tannous' 'Jonsson, Mr. Carl' 'Harris, Mr. George'
 'Appleton, Mrs. Edward Dale (Charlotte Lamson)'
 'Flynn, Mr. John Irwin ("Irving")' 'Kelly, Miss. Mary'
 'Rush, Mr. Alfred George John' 'Patchett, Mr. George'
 'Garside, Miss. Ethel' 'Silvey, Mrs. William Baird (Alice Munger)'
 'Caram, Mrs. Joseph (Maria Elias)' 'Jussila, Mr. Eiriik'
 'Christy, Miss. Julie Rachel'
 'Thayer, Mrs. John Borland (Marian Longstreth Morris)'
 'Downton, Mr. William James' 'Ross, Mr. John Hugo' 'Paulner, Mr. Uscher'
 'Taussig, Miss. Ruth' 'Jarvis, Mr. John Denzil'
 'Frolicher-Stehli, Mr. Maxmillian' 'Gilinski, Mr. Eliezer'
 'Murdlin, Mr. Joseph' 'Rintamaki, Mr. Matti'
 'Stephenson, Mrs. Walter Bertram (Martha Eustis)'
 'Elsbury, Mr. William James' 'Bourke, Miss. Mary'
 'Chapman, Mr. John Henry' 'Van Impe, Mr. Jean Baptiste'
 'Leitch, Miss. Jessie Wills' 'Johnson, Mr. Alfred' 'Boulos, Mr. Hanna'
 'Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")'
 'Jacobsohn, Mrs. Sidney Samuel (Amy Frances Christy)'
 'Slabenoff, Mr. Petco' 'Harrington, Mr. Charles H'
 'Torber, Mr. Ernst William' 'Homer, Mr. Harry ("Mr E Haven")'
 'Lindell, Mr. Edvard Bengtsson' 'Karaic, Mr. Milan'
 'Daniel, Mr. Robert Williams'
 'Laroche, Mrs. Joseph (Juliette Marie Louise Lafargue)'
 'Shutes, Miss. Elizabeth W'
 'Andersson, Mrs. Anders Johan (Alfrida Konstantia Brogren)'
 'Jardin, Mr. Jose Neto' 'Murphy, Miss. Margaret Jane' 'Horgan, Mr. John'
 'Brocklebank, Mr. William Alfred' 'Herman, Miss. Alice'
 'Danbom, Mr. Ernst Gilbert'
 'Lobb, Mrs. William Arthur (Cordelia K Stanlick)'
 'Becker, Miss. Marion Louise' 'Gavey, Mr. Lawrence' 'Yasbeck, Mr. Antoni'
 'Kimball, Mr. Edwin Nelson Jr' 'Nakid, Mr. Sahid'
 'Hansen, Mr. Henry Damsgaard' 'Bowen, Mr. David John "Dai"'
 'Sutton, Mr. Frederick' 'Kirkland, Rev. Charles Leonard'
 'Longley, Miss. Gretchen Fiske' 'Bostandyeff, Mr. Guentcho'
 "O'Connell, Mr. Patrick D" 'Barkworth, Mr. Algernon Henry Wilson'
 'Lundahl, Mr. Johan Svensson' 'Stahelin-Maeglin, Dr. Max'
 'Parr, Mr. William Henry Marsh' 'Skoog, Miss. Mabel' 'Davis, Miss. Mary'
 'Leinonen, Mr. Antti Gustaf' 'Collyer, Mr. Harvey'
 'Panula, Mrs. Juha (Maria Emilia Ojala)' 'Thorneycroft, Mr. Percival'
 'Jensen, Mr. Hans Peder' 'Sagesser, Mlle. Emma'
 'Skoog, Miss. Margit Elizabeth' 'Foo, Mr. Choong'
 'Baclini, Miss. Eugenie' 'Harper, Mr. Henry Sleeper' 'Cor, Mr. Liudevit'
 'Simonius-Blumer, Col. Oberst Alfons' 'Willey, Mr. Edward'
 'Stanley, Miss. Amy Zillah Elsie' 'Mitkoff, Mr. Mito'
 'Doling, Miss. Elsie' 'Kalvik, Mr. Johannes Halvorsen'
 'O\'Leary, Miss. Hanora "Norah"' 'Hegarty, Miss. Hanora "Nora"'

## 데이터 집계 및 그룹화

In [ ]:
titanic.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [ ]:
# 평균
titanic[['Age', 'Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

In [ ]:
# 합계
titanic[['Age', 'Fare']].sum()

Age     21205.1700
Fare    28693.9493
dtype: float64

In [ ]:
# 최솟값
titanic[['Age', 'Fare']].min()

Age     0.42
Fare    0.00
dtype: float64

In [ ]:
# groupby 객체 생성
titanic_groupby = titanic.groupby('Pclass')

# Age와 Fare에 대해 count(다양한 집계 연산 가능)
titanic_groupby[['Age', 'Fare']].count()

        Age  Fare
Pclass
1       186   216
2       173   184
3       355   491

In [ ]:
# 최대값과 최소값을 나란히 출력
titanic.groupby('Pclass')['Age'].max(), titanic.groupby('Pclass')['Age'].min()

(Pclass
 1    80.0
 2    70.0
 3    74.0
 Name: Age, dtype: float64,
 Pclass
 1    0.92
 2    0.67
 3    0.42
 Name: Age, dtype: float64)

In [ ]:
# max, min 함께 보기
titanic.groupby('Pclass')['Age'].agg(['max', 'min'])

         max   min
Pclass
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [ ]:
titanic.groupby(['Pclass']).agg(
    age_max=('Age', 'max'),
    age_mean=('Age', 'mean'),
    fare_mean=('Fare', 'mean')
)

        age_max   age_mean  fare_mean
Pclass
1          80.0  38.233441  84.154687
2          70.0  29.877630  20.662183
3          74.0  25.140620  13.675550

In [ ]:
agg_format = {
    'Age': 'max',
    'SibSp': 'sum',
    'Fare': 'mean'
}
titanic.groupby('Pclass').agg(agg_format)

         Age  SibSp       Fare
Pclass
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

In [ ]:
# apply를 통한 이름 길이 계산
titanic['Name_len'] = titanic['Name'].apply(lambda x: len(x))
titanic[['Name', 'Name_len']].head()

                                                Name  Name_len
0                            Braund, Mr. Owen Harris        23
1  Cumings, Mrs. John Bradley (Florence Briggs Th...        51
2                             Heikkinen, Miss. Laina        22
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)        44
4                           Allen, Mr. William Henry        24

In [ ]:
# 나이 기준으로 아동/성인 구분
titanic['Child_Adult'] = titanic['Age'].apply(lambda x: 'Child' if x <= 19 else 'Adult')
titanic[['Age', 'Child_Adult']].tail()

      Age Child_Adult
886  27.0       Adult
887  19.0       Child
888   NaN       Adult
889  26.0       Adult
890  32.0       Adult

In [ ]:
def categorize_age(age):
    """
    나이에 따라 연령대를 분류하는 함수
    """
    if age <= 5:
        return 'Baby'
    elif age <= 12:
        return 'Child'
    elif age <= 18:
        return 'Teenager'
    elif age <= 25:
        return 'Student'
    elif age <= 35:
        return 'Young Adult'
    elif age <= 60:
        return 'Adult'
    else:
        return 'Elderly'

# 적용 및 확인
titanic['Categorized_Age'] = titanic['Age'].apply(categorize_age)
titanic[['Age', 'Categorized_Age']].head()

    Age Categorized_Age
0  22.0         Student
1  38.0           Adult
2  26.0     Young Adult
3  35.0     Young Adult
4  35.0     Young Adult

## 데이터 병합 및 변환

In [ ]:
import pandas as pd

df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                    'B': ['B0', 'B1', 'B2']})

df2 = pd.DataFrame({'C': ['C0', 'C1', 'C2'],
                    'D': ['D0', 'D1', 'D2']})

df3 = pd.concat([df1, df2], axis=0)  # 행 병합
df4 = pd.concat([df1, df2], axis=1)  # 열 병합

print(df1)
print('\n')
print(df2)
print('\n')
print(df3)
print('\n')
print(df4)

    A   B
0  A0  B0
1  A1  B1
2  A2  B2


    C   D
0  C0  D0
1  C1  D1
2  C2  D2


     A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1
2  NaN  NaN   C2   D2


    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2

In [ ]:
df1 = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                    'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3']})

df2 = pd.DataFrame({'key': ['K0', 'K1', 'K2'],
                    'C': ['C0', 'C1', 'C2'],
                    'D': ['D0', 'D1', 'D2']})

df_merged = pd.merge(df1, df2, on='key', how='inner')

print(df1)
print('\n')
print(df2)
print('\n')
print(df_merged)

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3


  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2


  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2

In [ ]:
df1 = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                    'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3']})

df2 = pd.DataFrame({'key': ['K0', 'K1', 'K2'],
                    'C': ['C0', 'C1', 'C2'],
                    'D': ['D0', 'D1', 'D2']})

df_merged = pd.merge(df1, df2, on='key', how='outer')

print(df1)
print('\n')
print(df2)
print('\n')
print(df_merged)

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3


  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2


  key   A   B    C    D
0  K0  A0  B0   C0   D0
1  K1  A1  B1   C1   D1
2  K2  A2  B2   C2   D2
3  K3  A3  B3  NaN  NaN

In [ ]:
df1 = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                    'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3']})

df2 = pd.DataFrame({'key': ['K0', 'K1', 'K2'],
                    'C': ['C0', 'C1', 'C2'],
                    'D': ['D0', 'D1', 'D2']})

df_merged = pd.merge(df1, df2, on='key', how='left')

print(df1)
print('\n')
print(df2)
print('\n')
print(df_merged)

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3


  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2


  key   A   B    C    D
0  K0  A0  B0   C0   D0
1  K1  A1  B1   C1   D1
2  K2  A2  B2   C2   D2
3  K3  A3  B3  NaN  NaN

In [ ]:
df1 = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                    'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3']})

df2 = pd.DataFrame({'key': ['K0', 'K1', 'K2'],
                    'C': ['C0', 'C1', 'C2'],
                    'D': ['D0', 'D1', 'D2']})

df_merged = pd.merge(df1, df2, on='key', how='right')

print(df1)
print('\n')
print(df2)
print('\n')
print(df_merged)

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3


  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2


  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2

In [ ]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2']
}, index=['K0', 'K1', 'K2'])

df2 = pd.DataFrame({
    'C': ['C0', 'C1', 'C2'],
    'D': ['D0', 'D1', 'D2']
}, index=['K0', 'K2', 'K3'])

df_merged = df1.join(df2, how='left')

print(df1)
print('\n')
print(df2)
print('\n')
print(df_merged)

     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2


     C   D
K0  C0  D0
K2  C1  D1
K3  C2  D2


     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C1   D1

In [ ]:
sales = pd.DataFrame({
    'customer_id': [1, 2, 3, 4],
    'product_id': [101, 102, 103, 104],
    'quantity': [5, 2, 3, 1]
})

customers = pd.DataFrame({
    'customer_id': [1, 2, 3, 5],
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'city': ['Seoul', 'Busan', 'Daegu', 'Incheon']
})

# 인덱스 customer_id로 설정
sales = sales.set_index('customer_id')
customers = customers.set_index('customer_id')

# Left Join
merged_data = sales.join(customers, how='left')

print(sales)
print('\n')
print(customers)
print('\n')
print(merged_data)

             product_id  quantity
customer_id
1                   101         5
2                   102         2
3                   103         3
4                   104         1


                name     city
customer_id
1              Alice    Seoul
2                Bob    Busan
3            Charlie    Daegu
5              David  Incheon


             product_id  quantity     name   city
customer_id
1                   101         5    Alice  Seoul
2                   102         2      Bob  Busan
3                   103         3  Charlie  Daegu
4                   104         1      NaN    NaN

In [ ]:
df1 = pd.DataFrame({
    'key': ['K0', 'K1', 'K2', 'K3'],
    'A': ['A0', 'A1', 'A2', 'A3'],
    'C': ['C0', 'C1', 'C2', 'C3']
})

df2 = pd.DataFrame({
    'key': ['K0', 'K1', 'K2'],
    'C': ['C4', 'C5', 'C6'],
    'D': ['D0', 'D1', 'D2']
})

df_merged = pd.merge(df1, df2, on='key', how='inner', suffixes=('_left', '_right'))

print(df1)
print('\n')
print(df2)
print('\n')
print(df_merged)

  key   A   C
0  K0  A0  C0
1  K1  A1  C1
2  K2  A2  C2
3  K3  A3  C3


  key   C   D
0  K0  C4  D0
1  K1  C5  D1
2  K2  C6  D2


  key   A C_left C_right   D
0  K0  A0     C0      C4  D0
1  K1  A1     C1      C5  D1
2  K2  A2     C2      C6  D2

In [ ]:
df1 = pd.DataFrame({
    'key': ['K0', 'K1', 'K2', 'K3'],
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3']
})

df2 = pd.DataFrame({
    'key': ['K0', 'K1', 'K2'],
    'C': ['C0', 'C1', 'C2'],
    'D': ['D0', 'D1', 'D2']
})

df_merged = pd.merge(df1, df2, on='key', how='inner')
df_merged = df_merged.drop('B', axis=1)

print(df1)
print('\n')
print(df2)
print('\n')
print(df_merged)

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3


  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2


  key   A   C   D
0  K0  A0  C0  D0
1  K1  A1  C1  D1
2  K2  A2  C2  D2

In [ ]:
df1 = pd.DataFrame({
    'key1': ['K0', 'K1', 'K2', 'K3'],
    'key2': ['K4', 'K5', 'K6', 'K7'],
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3']
})

df2 = pd.DataFrame({
    'key1': ['K0', 'K1', 'K2'],
    'key2': ['K4', 'K5', 'K6'],
    'C': ['C0', 'C1', 'C2'],
    'D': ['D0', 'D1', 'D2']
})

df_merged = pd.merge(df1, df2, on=['key1', 'key2'], how='inner')

print(df1)
print('\n')
print(df2)
print('\n')
print(df_merged)

  key1 key2   A   B
0   K0   K4  A0  B0
1   K1   K5  A1  B1
2   K2   K6  A2  B2
3   K3   K7  A3  B3


  key1 key2   C   D
0   K0   K4  C0  D0
1   K1   K5  C1  D1
2   K2   K6  C2  D2


  key1 key2   A   B   C   D
0   K0   K4  A0  B0  C0  D0
1   K1   K5  A1  B1  C1  D1
2   K2   K6  A2  B2  C2  D2

In [ ]:
import pandas as pd

# Titanic 데이터 CSV 파일 로드
titanic = pd.read_csv("./data/titanic.csv")

In [ ]:
# Titanic 데이터
titanic['Sex'] = titanic['Sex'].replace({'male': 'Man', 'female': 'Woman'})
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",Man,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Woman,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Woman,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Woman,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",Man,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
# Embarked 값 개수 확인
titanic['Embarked'].value_counts(dropna=False)

Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

In [ ]:
import numpy as np

# NaN을 특정 값으로 대체
titanic['Embarked'] = titanic['Embarked'].replace(np.nan, 'S')

# Cabin별 값 개수 확인
titanic['Embarked'].value_counts(dropna=False)

Embarked
S    646
C    168
Q     77
Name: count, dtype: int64

In [ ]:
# 성별(Sex) × 객실등급(Pclass)별 평균 나이(Age) - pivot
pivot_df = titanic.groupby(['Sex', 'Pclass'])['Age'].mean().reset_index()
pivot_table = pivot_df.pivot(index='Sex', columns='Pclass', values='Age')
pivot_table

Pclass          1          2          3
Sex
Man     41.281386  30.740707  26.507589
Woman   34.611765  28.722973  21.750000

In [ ]:
# 성별(Sex) × 객실등급(Pclass) 별 평균 나이(Age) - pivot_table
titanic.pivot_table(
    index='Sex',
    columns='Pclass',
    values='Age',
    aggfunc='mean'
)

Pclass          1          2          3
Sex
Man     41.281386  30.740707  26.507589
Woman   34.611765  28.722973  21.750000

In [ ]:
# 성별(Sex) × 생존여부(Survived) 별 평균 요금(Fare)
titanic.pivot_table(
    index='Sex',
    columns='Survived',
    values='Fare',
    aggfunc='mean'
)

Survived          0          1
Sex
Man       21.960993  40.821484
Woman     23.024385  51.938573

#### melt

| Survived | SibSp | Parch |
| -------- | ----- | ----- |
| 1        | 1     | 0     |

형태에서

| Survived | family_type | count |
| -------- | ----------- | ----- |
| 1        | SibSp       | 1     |
| 1        | Parch       | 0     |

형태로 변환

In [ ]:
# Wide-format → Long-format 변환
# 여러 개의 가족 관련 변수(sibsp, parch)를 하나의 범주형 변수(family_type)로 묶어서 분석
melted_family = pd.melt(
    titanic,
    id_vars=['Survived'],
    value_vars=['SibSp', 'Parch'],
    var_name='family_type',
    value_name='count'
)

melted_family

      Survived family_type  count
0            0       SibSp      1
1            1       SibSp      1
2            1       SibSp      0
3            1       SibSp      1
4            0       SibSp      0
...        ...         ...    ...
1777         0       Parch      0
1778         1       Parch      0
1779         0       Parch      2
1780         1       Parch      0
1781         0       Parch      0

[1782 rows x 3 columns]